apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-blog
  template:
    metadata:
      labels:
        app: my-blog
    spec:
      containers:
        - name: my-blog
          image: my_blog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-blog
spec:
  selector:
    app: my-blog
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-blog
spec:
  ingressClassName: traefik
  rules:
    - host: wnaseeve.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-blog
                port:
                  number: 80

